Repository octokit/rest.js, pull requests merged in 2022-06, with the labels that each got.

#140 build: updates lock file from old generation and applies lint fixes to the security policy
  SECURITY.md
  package-lock.json
Labels: documentation, maintenance

#152 build(npm): replace 'pika' command with 'pika-pack'
  package.json
Labels: maintenance

#154 ci(codeql): ignore on push events for dependabot branches
  .github/workflows/codeql.yml
Labels: bug

#153 ci(codeql): ignore on push events for dependabot branches
  .github/workflows/codeql.yml
Labels: bug
