Repository octokit/rest.js, pull requests merged in 2023-06, with the labels that each got.

#294 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
Labels: Type: Maintenance, Type: Breaking change

#317 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation

#320 fix(deps): revert breaking dependency changes
  package-lock.json
  package.json
Labels: Type: Maintenance
